### ISSUE TITLE
Error: File '/**/estop-release/node_modules/blessed/usr/xterm' was not included into executable at compilation stage. Please recompile adding it as asset or script.

### ISSUE THREAD

**Issue by Hubbitus** [opendistro-for-elasticsearch/perftop#36]
Download https://d3g5vo6xdbdb9a.cloudfront.net/downloads/perftop/perf-top-1.4.0.0-LINUX.zip

Try start:
```
$ chmod +x perf-top-linux
$ ./perf-top-linux --dashboard NodeAnalysis
pkg/prelude/bootstrap.js:1178
      throw error;
      ^

Error: File '/**/estop-release/node_modules/blessed/usr/xterm' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:422:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:650:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:693:18)
    at Tput.readTerminfo (/snapshot/estop-release/node_modules/blessed/lib/tput.js:149:13)
    at Tput.compileTerminfo (/snapshot/estop-release/node_modules/blessed/lib/tput.js:616:28)
    at Tput.injectTerminfo (/snapshot/estop-release/node_modules/blessed/lib/tput.js:620:27)
    at Tput._useXtermInfo (/snapshot/estop-release/node_modules/blessed/lib/tput.js:111:15)
    at Tput.setup (/snapshot/estop-release/node_modules/blessed/lib/tput.js:85:10)
    at new Tput (/snapshot/estop-release/node_modules/blessed/lib/tput.js:60:10)
    at Program.setupTput (/snapshot/estop-release/node_modules/blessed/lib/program.js:210:26)
```

**Comment by Hubbitus** [comment]
Sorry, looks like duplicate of https://github.com/opendistro-for-elasticsearch/perftop/issues/29
